<?php
include( 'include/ini.php' );
$gameController = new GameController;
$gameController->loadGame(4);
$gameController->getGame()->getHerosActif()->draw(4);
$gameController->getGame()->getHerosInactif()->draw(4);
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->pass();
$gameController->getGame()->attack( 84, 105 );

include( 'modules/game/board.php');
